# Generated by Django 2.0.7 on 2018-07-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetag',
            name='sorting_order',
            field=models.IntegerField(default=99),
        ),
    ]
