# Generated by Django 2.0.7 on 2018-07-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_templatetag_sorting_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttablecolumn',
            old_name='sql_table',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='documenttablecolumn',
            old_name='sql_query',
            new_name='values',
        ),
    ]
