# Generated by Django 2.0.7 on 2018-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180708_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttablecolumn',
            name='values',
            field=models.TextField(),
        ),
    ]
