# Generated by Django 2.0.7 on 2018-07-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20180708_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
