# Generated by Django 2.0.7 on 2018-07-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.State'),
        ),
    ]
