# Generated by Django 2.0.7 on 2018-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sorting_order',
            field=models.IntegerField(default=99),
        ),
    ]
