# Generated by Django 2.0.7 on 2018-07-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_data_sorting_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['template_tag__sorting_order']},
        ),
        migrations.RemoveField(
            model_name='data',
            name='sorting_order',
        ),
    ]
