# Generated by Django 2.0.7 on 2018-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20180717_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='extra_data_label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
