# Generated by Django 2.0.7 on 2018-07-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_eventpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='documents.State'),
        ),
    ]
