# Generated by Django 2.0.7 on 2018-07-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20180719_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpermission',
            name='allow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='documents.State'),
        ),
    ]
