# Generated by Django 2.0.7 on 2018-08-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20180719_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.Template'),
        ),
    ]
